package b1_03;

import b1_03.objetos.Terreno;
import static b1_03.utilidades.ES_de_archivos.escribir_linea;
import static b1_03.utilidades.ES_de_archivos.leer_archivo;
import static b1_03.utilidades.Miscelanea.crearTerreno;
import static b1_03.utilidades.Miscelanea.esValido;
import static b1_03.utilidades.Resolucion.algoritmoDeBusqueda;
import static b1_03.utilidades.Resolucion.algoritmoProfundidadIterativa;
import excepciones.EscrituraErronea;
import excepciones.LecturaErronea;
import static java.awt.EventQueue.invokeLater;
import java.awt.HeadlessException;
import static java.lang.System.arraycopy;
import java.security.NoSuchAlgorithmException;
import java.util.LinkedList;
import static java.util.logging.Level.SEVERE;
import static java.util.logging.Logger.getLogger;
import javax.swing.JFileChooser;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;

/**
 * @author Alfonso Barragán
 * @author Francisco Manuel García
 * @author Marcos López
 *
 * @version 1.0.0
 */
public class MainWindow extends javax.swing.JFrame {

    private String solucion = "";
    private String ruta;

    /**
     * Creates new form MainnWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        btnIniciar = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();
        cbAlgoritmo = new javax.swing.JComboBox<>();
        btnGuardarSol = new javax.swing.JButton();
        spnProfMax = new javax.swing.JSpinner();
        spnIncProf = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCargarTerreno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Distribuidor");
        setResizable(false);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        btnIniciar.setText("Iniciar");
        btnIniciar.setEnabled(false);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        cbAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anchura", "Profundidad", "C. Uniforme", "A*", "Voraz", "P. Iterativa" }));
        cbAlgoritmo.setEnabled(false);
        cbAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlgoritmoActionPerformed(evt);
            }
        });

        btnGuardarSol.setText("Guardar solucion");
        btnGuardarSol.setEnabled(false);
        btnGuardarSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSolActionPerformed(evt);
            }
        });

        spnProfMax.setModel(new javax.swing.SpinnerNumberModel(50, 50, null, 50));
        spnProfMax.setEnabled(false);

        spnIncProf.setModel(new javax.swing.SpinnerNumberModel(10, 10, null, 15));
        spnIncProf.setEnabled(false);

        jLabel1.setText("Prof. Max.");

        jLabel2.setText("Inc. Prof");

        btnCargarTerreno.setText("Cargar terreno");
        btnCargarTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTerrenoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbAlgoritmo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnProfMax, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnIncProf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargarTerreno))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnGuardarSol)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarTerreno))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnProfMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnIncProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarSol, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * El siguiente métodos es el escuchador de la pulsación del botón Inicio.
     * Este método se encarga de arrancar todos los componentes necesarios para
     * la resolución del problema. Dentro de la clase se puede encontrar más
     * documentación.
     *
     * @param evt
     */
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        Terreno t; // Terreno inicial

        // Vector resultado de la lectura del fichero
        int[] datos = null;
        try {
            datos = leer_archivo(ruta);
            int k = datos[2]; // Cantidad objetivo de arena
            int max = datos[3]; // Cantidad máxima de arena

            int fs = datos[4]; // Número de filas
            int cs = datos[5]; // Número de columnas

            // Vector auxiliar donde posteriormente copiamos el segmento del vector datos
            // que se corresponde con la cantidad inicial de arena en cada casilla
            int[] aux = new int[fs * cs];
            arraycopy(datos, 6, aux, 0, aux.length);

            // Comprobamos validez del terreno, y si lo es, lo creamos.
            if (!esValido(fs, cs, k, aux, max)) {
                txtSalida.setText("ERROR: El terreno cargado es incorrecto.");
            } else {

                t = crearTerreno(aux, fs, cs, datos[1], datos[0], k);

                // Se muestran los datos del fichero
                txtSalida.append("k: " + k + ", max: " + max + ", fs: " + fs + ", cs: " + cs);
                txtSalida.append(t.toString());

                try {

                    // Resto de algoritmos
                    if (cbAlgoritmo.getSelectedIndex() != 5) {
                        solucion = algoritmoDeBusqueda(t, cbAlgoritmo.getSelectedIndex(), k, fs, cs, max, 999_999_999, txtSalida);
                    } else {
                        solucion = algoritmoProfundidadIterativa(t, 1, (int) spnProfMax.getValue(), (int) spnIncProf.getValue(), k, fs, cs, max, txtSalida);
                    }

                    txtSalida.append(solucion);

                    btnGuardarSol.setEnabled(true);
                    // Profundidad iterativa
                    //System.out.println("\n"+Resolucion.algoritmoProfundidadIterativa(t, 1, 999999999, 150, k, fs, cs, max));
                } catch (NoSuchAlgorithmException ex) {
                    getLogger(MainWindow.class.getName()).log(SEVERE, null, ex);
                }

            }

        } catch (LecturaErronea ex) {
            txtSalida.setText("Archivo no encontrado-> " + ruta);
        }

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnGuardarSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSolActionPerformed

        JFileChooser jfch = new JFileChooser();
        try {
            if (jfch.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                ruta = jfch.getSelectedFile().getAbsolutePath();
                escribir_linea(ruta, true, solucion);
            }
        } catch (EscrituraErronea | HeadlessException ex) {
            txtSalida.append("Error al guardar fichero -> " + ruta);
        }
    }//GEN-LAST:event_btnGuardarSolActionPerformed

    private void cbAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlgoritmoActionPerformed
        if (cbAlgoritmo.getSelectedIndex() == 5) {
            spnIncProf.setEnabled(true);
            spnProfMax.setEnabled(true);
        } else {
            spnIncProf.setEnabled(false);
            spnProfMax.setEnabled(false);
        }
        btnIniciar.setEnabled(true);
    }//GEN-LAST:event_cbAlgoritmoActionPerformed

    private void btnCargarTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTerrenoActionPerformed
        JFileChooser jfch = new JFileChooser();
        try {
            if (jfch.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                ruta = jfch.getSelectedFile().getAbsolutePath();
                txtPath.setText(ruta.substring(ruta.lastIndexOf("\\") + 1, ruta.length()));
                cbAlgoritmo.setEnabled(true);
            }
        } catch (HeadlessException ex) {
            txtSalida.append("Error al cargar fichero -> " + ruta);
        }
    }//GEN-LAST:event_btnCargarTerrenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(MainWindow.class.getName()).log(SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarTerreno;
    private javax.swing.JButton btnGuardarSol;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JComboBox<String> cbAlgoritmo;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnIncProf;
    private javax.swing.JSpinner spnProfMax;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
