/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package b1_03;

import b1_03.objetos.Terreno;
import static b1_03.utilidades.ES_de_archivos.escribir_linea;
import static b1_03.utilidades.ES_de_archivos.leer_archivo;
import static b1_03.utilidades.Miscelanea.crearTerreno;
import static b1_03.utilidades.Miscelanea.esValido;
import static b1_03.utilidades.Resolucion.algoritmoDeBusqueda;
import static b1_03.utilidades.Resolucion.algoritmoProfundidadIterativa;
import excepciones.EscrituraErronea;
import excepciones.LecturaErronea;
import static java.awt.EventQueue.invokeLater;
import static java.lang.System.arraycopy;
import java.security.NoSuchAlgorithmException;
import java.util.LinkedList;
import static java.util.logging.Level.SEVERE;
import static java.util.logging.Logger.getLogger;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;

/**
 *
 * @author pacog
 */
public class MainWindow extends javax.swing.JFrame {

    private String solucion = "";

    /**
     * Creates new form MainnWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        iniciar = new javax.swing.JButton();
        pathField = new javax.swing.JTextField();
        algoritmoCombobox = new javax.swing.JComboBox<>();
        guardarTextField = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        profMaxSpinner = new javax.swing.JSpinner();
        incProfSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane1.setViewportView(salida);

        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        pathField.setText("terreno_2.txt");

        algoritmoCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anchura", "Profundidad", "C. Uniforme", "A*", "Voraz", "P. Iterativa" }));
        algoritmoCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoritmoComboboxActionPerformed(evt);
            }
        });

        guardarTextField.setText("solucion.txt");

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        profMaxSpinner.setModel(new javax.swing.SpinnerNumberModel(50, 50, null, 50));
        profMaxSpinner.setEnabled(false);

        incProfSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 10, null, 15));
        incProfSpinner.setEnabled(false);

        jLabel1.setText("Prof. Max.");

        jLabel2.setText("Inc. Prof");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(algoritmoCombobox, 0, 95, Short.MAX_VALUE)
                    .addComponent(profMaxSpinner)
                    .addComponent(incProfSpinner)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardarTextField)
                    .addComponent(pathField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pathField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(algoritmoCombobox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guardarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(guardarTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iniciar)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profMaxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incProfSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        salida.setText("");
        // Lista donde iremos guardando los terrenos generados tras cada acción
        LinkedList<Terreno> lt = new LinkedList<>();

        Terreno t; // Terreno inicial

        // Vector resultado de la lectura del fichero
        int[] datos = null;
        try {
            datos = leer_archivo(pathField.getText());
            int k = datos[2]; // Cantidad objetivo de arena
            int max = datos[3]; // Cantidad máxima de arena

            int fs = datos[4]; // Número de filas
            int cs = datos[5]; // Número de columnas

            // Vector auxiliar donde posteriormente copiamos el segmento del vector datos
            // que se corresponde con la cantidad inicial de arena en cada casilla
            int[] aux = new int[fs * cs];
            arraycopy(datos, 6, aux, 0, aux.length);

            // Comprobamos validez del terreno, y si lo es, lo creamos.
            if (!esValido(fs, cs, k, aux, max)) {
                salida.setText("ERROR: Los datos son incorrectos.");
            } else {

                t = crearTerreno(aux, fs, cs, datos[1], datos[0], k);

                lt.add(t); // Añadimos el terreno inicial a la lista

                // MUESTRA DE LOS DATOS RECOGIDOS Y PROCESADOS
                salida.append("k: " + k + ", max: " + max + ", fs: " + fs + ", cs: " + cs);
                salida.append(t.toString());

                try {
                    /*la = GestorAcciones.generarAcciones(t, k, fs, cs, max);
                
                // Mostramos las acciones
                Iterator<Accion> itact = la.iterator();
                while (itact.hasNext()) {
                System.out.println(itact.next());
                }*/

                    // Resto de algoritmos
                    if (algoritmoCombobox.getSelectedIndex() != 5) {
                        solucion = algoritmoDeBusqueda(t, algoritmoCombobox.getSelectedIndex(), k, fs, cs, max, 999_999_999, salida);
                    } else {
                        solucion = algoritmoProfundidadIterativa(t, 1,(int)profMaxSpinner.getValue(),(int)incProfSpinner.getValue(), k, fs, cs, max, salida);
                    }

                    salida.append(solucion);
                    // Profundidad iterativa
                    //System.out.println("\n"+Resolucion.algoritmoProfundidadIterativa(t, 1, 999999999, 150, k, fs, cs, max));
                } catch (NoSuchAlgorithmException ex) {
                    getLogger(MainWindow.class.getName()).log(SEVERE, null, ex);
                }

            }

        } catch (LecturaErronea ex) {
            salida.setText("Archivo no encontrado-> " + pathField.getText());
        }


    }//GEN-LAST:event_iniciarActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        try {
            escribir_linea(guardarTextField.getText(), true, solucion);
        } catch (EscrituraErronea ex) {
            salida.append("Error al guardar.");
        }
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void algoritmoComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoritmoComboboxActionPerformed
        if (algoritmoCombobox.getSelectedIndex() == 5) {
            incProfSpinner.setEnabled(true);
            profMaxSpinner.setEnabled(true);
        } else {
            incProfSpinner.setEnabled(false);
            profMaxSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_algoritmoComboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(MainWindow.class.getName()).log(SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> algoritmoCombobox;
    private javax.swing.JButton guardarButton;
    private javax.swing.JTextField guardarTextField;
    private javax.swing.JSpinner incProfSpinner;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pathField;
    private javax.swing.JSpinner profMaxSpinner;
    private javax.swing.JTextArea salida;
    // End of variables declaration//GEN-END:variables
}
